### ISSUE TITLE
ssl.SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:2635)

### ISSUE THREAD

**Issue by JunZhan2000** [qywu/FaceChat#1]
I have installed all dependencies and run the server, but when the server receives a request, it throws an error ssl.SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:2635).
 I executed the command `openssl req -x509 -newkey rsa:4096 -nodes -out cert.pem -keyout key.pem -days 365`  to generate a self-signed certificate and it created two files cert.pem and key.pem in the current directory. Is there any impact if I fill in the values arbitrarily when setting them?

**Comment by qywu** [comment]
If you are testing it on your local machine, it will not have any impact with the self-assigned certificate and you should have access with no problem. If you want to make it public, then it is better to use a real certificate.

**Comment by JunZhan2000** [comment]
I test in mac, after I manually import the self-assigned certificate to Safari, it works
